---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xenonepa/xenonepal/
    - /bin/cp -r src/* $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json  $DEPLOYPATH